<div class="partners">
    <div class= "partners__logo">
        <div class="partners__logo-container row">
            <a href="#" title="Graphic design">
                <img class="partners__logo-content col-1-4" src='<?php echo $this->getViewFileUrl('images/graphic-design.png'); ?>' alt="Graphic design">
            </a>
            <a href="#" title="Euismoe">
                <img class="partners__logo-content col-1-4" src='<?php echo $this->getViewFileUrl('images/euismoe.png'); ?>' alt="Euismoe">
            </a>
            <a href="#" title="Surfwearncy">
                <img class="partners__logo-content col-1-4" src='<?php echo $this->getViewFileUrl('images/surfwearncy.png'); ?>' alt="Surfwearncy">
            </a>
            <a href="#" title="Pacificom">
                <img class="partners__logo-content col-1-4" src='<?php echo $this->getViewFileUrl('images/pacificom.png'); ?>' alt="Pacificom">
            </a>
        </div>
    </div>
</div>
<div class="formulario">
    <img class="icon-airplane" src='<?php echo $this->getViewFileUrl('images/icon-airplane.png'); ?>' alt="Icon airplane">
    <p class="msg-email">Sign up to receive our news and promotions by email:</p>
    <form class="form" action="#">
        <label class="input-newsletter" for="newsletter">
            <input id="newsletter" name="email" type="email" placeholder="Enter your email address">
        <label>
        <button class="action subscribe primary" title="Send" type="submit">Subscribe</button>
</div>