<div class="img-history">
    <div class="history-first-project">
        <h1 class= "title-history"> Brief History </h1>
        <p class="history">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam natus iste ex suscipit, facere ratione porro, consectetur, deleniti esse magni dolorem nobis ea asperiores veritatis nisi? Laudantium temporibus ad at.  
        </p>
        <p class="history">
        Suspendisse dignissim nibh eget justo aliquam pellentesque. Morbi id turpis quis nisl fermentum egestas. Nam sollicitudin vestibulum nunc ac mattis. Donec ut tincidunt mauris. Donec sed dignissim nisl. Vestibulum vel neque at odio varius dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi tincidunt at libero sed sollicitudin. Vestibulum in egestas elit, ornare varius quam. Mauris tristique leo leo, sit amet fringilla erat ultrices in. 
        </p>
        <p class="author-history">Lorem ipsum</p>
    </div>
</div>